title: "Personality Quiz"
description: "Lorem Ipsum"
theme: minima

markdown: kramdown
permalink: pretty
header_pages: [""]

minima:
  skin: auto
  social_links:
    - platform: github
      user_url: "https://github.com/hanziertoo"

author: "Hanzier"

exclude:
  - README.md
  - node_modules
  - Gemfile
  - Gemfile.lock
