title: "Personality Quiz"
description: "© 2024 SchizCo Consulting Group. All rights reserved. All lefts taken."
theme: minima

markdown: kramdown
permalink: pretty
header_pages: [""]

minima:
  skin: auto
  social_links:
    - platform: github
      user_url: "https://github.com/hanziertoo"

author: "Personality G-8427"

exclude:
  - README.md
  - node_modules
  - Gemfile
  - Gemfile.lock
